### ISSUE TITLE
number of proposals

### ISSUE THREAD

**Issue by fizamurtaza** [shyamal-b/sst#3]
hello,

As you mentioned in your paper that 
"**sequence encoder outputs k proposals at each time step t with a confidence vector ct, where the longest proposal is of length δ · k.** "

My question is if a time step have size of δ (16) frames then how the longest proposal can have size of δ.k?? 

kindly can you explain this? I tried to understand many times but failed :(

**Comment by shyamal-b** [comment]
Hi @fizamurtaza ,

Sure thing! A key aspect of the model is that the goal of the sequence encoder at time step _t_ should be to maintain the necessary _context_ (or "memory") from the previous time steps (1, ... , _t-1_) so that the model can provide proposals scores over the longer time spans. This context is maintained in the hidden state of the recurrent network. Using this context, we can obtain the final scores over all the temporal anchors/scales directly, even when the starting point is several time steps prior. 

Intuitively, this is similar to how if you were to watch a video and see an action end, you can _remember_ when that action started, even if it was several seconds prior to the current point.
