### ISSUE TITLE
.hdf5 format

### ISSUE THREAD

**Issue by dhlee-jubilee** [shyamal-b/sst#6]
I'd like to try train THUMOS14 video datasets as you did.
But I'm embarrassed that the video input type is not .avi or .mp4 but .hdf5 format.
I'm not familiar with .hdf5 format, so requesting you some converting tip.

Besides, I downloaded THUMOS15 video 'Test Data(untrimmed)' as your journal.
Sadly, to unzip the data, it is required password, but the THUMOS Challenge 2014 is closed a few years ago. So, if you know I request the password as well! Thanks.

Best,

dongheon Lee

**Comment by shyamal-b** [comment]
Hi @dhlee-jubilee ,

HDF5 is a generic (not video format-specific) efficient way of storing numpy arrays (e.g. visual encoder features, frame data, etc.) that correspond to some key (e.g. video_id string). You can take a look at [h5py](http://www.h5py.org/) and [hickle](https://github.com/telegraphic/hickle) for some examples on how to use them with your data. 

In your case, you can do a pipeline like (1) use `ffmpeg` to extract RGB frames from your video.mp4 to image files, (2) use standard PIL or equivalent to load the images into numpy arrays (and if you want, pass them through some visual encoder to obtain features for lower disk space usage), and (3) store that in an hdf5 file. Also, since the SST code here is generic, you can also do whatever you prefer for converting/storing numpy arrays and just pass those in (and fit the input loading code to whatever your pipeline is).

Regarding test set password, you have to contact the challenge organizers directly with your lab affiliation info, etc. and they will send you the password information. For details, you can refer to the "Password" section on [this THUMOS14 challenge webpage](http://crcv.ucf.edu/THUMOS14/download.html).
